---

# Include all needed .env files
include:

    # Global env only
    - path: traefik/compose.yaml 
      env_file:
        ./.env
    - path: filebrowser/compose.yaml
      env_file:
        ./.env
    - path: ghostboard/compose.yaml
      env_file:
        ./.env
    - path: ittools/compose.yaml
      env_file:
        ./.env

    # Global and local env
    - path: rxresume/compose.yaml
      env_file:
        ./.env
        ./rxresume/.env
    - path: papra/compose.yaml
      env_file:
        ./.env
        ./papra/.env

  # DISABLED CONTAINERS
    # - path: portainer/compose.yaml
    #   env_file:
    #     ./.env
    #     ./portainer/.env

# Create proxy network for use with traefik
networks:
  proxy:

# Define all docker containers
services:

  # Proxy
  traefik:
    extends:
      file: traefik/compose.yaml
      service: traefik
      env_file:
        - ./.env

  # Service Containers
  filebrowser:
    extends:
      file: filebrowser/compose.yaml
      service: filebrowser
      env_file:
        - ./.env

  ghostboard:
    extends:
      file: ghostboard/compose.yaml
      service: ghostboard
      env_file:
        - ./.env

  ittools:
    extends:
      file: ittools/compose.yaml
      service: ittools
      env_file:
        - ./.env

# DISABLED CONTAINERS

  # rxresume:
  #   extends:
  #     file: rxresume/compose.yaml
  #     service: rxresume
  #     env_file:
  #       - ./.env
  #       - ./rxresume/.env

  # papra:
  #   extends:
  #     file: papra/compose.yaml
  #     service: papra
  #     env_file:
  #       - ./.env
  #       - ./papra/.env

  # portainer:
  #   extends:
  #     file: portainer/compose.yaml
  #     service: portainer