---
services:
  ghostboard:
    container_name: ghostboard
    image: thehelpfulidiot/ghostboard-server
    restart: unless-stopped
    # ports:
    #     - 8080:8080
    #     - 8765:8765
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ghostboard.rule=Host(`ghostboard.lan`)"
      - "traefik.http.services.ghostboard.loadbalancer.server.port=80"
    
networks:
  proxy:
    external: true   
