---
services:
  commafeed:
    image: athou/commafeed:latest-h2
    container_name: commafeed
    # ports:
    #  - 8082:8082
    volumes:
      - ${}/commafeed/data:/commafeed/data
    deploy:
      resources:
        limits:
          memory: 256M
    restart: unless-stopped

    # TRAEFIK
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.commafeed.rule=Host(`commafeed.${DOMAIN}`)"
      - "traefik.http.routers.commafeed.entrypoints=https"
      - "traefik.http.routers.commafeed.tls=true"
      - "traefik.http.services.commafeed.loadbalancer.server.port=8082"

networks:
  proxy:
    external: true